export default ScreenName = {
  AUTH_SCREEN: 'AUTH_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  LOVE_SCREEN: 'LOVE_SCREEN',
  USER_SCREEN: 'USER_SCREEN',
  CART_SCREEN: 'CART_SCREEN',
  MORE_PRODUCT_SCREEN: 'MORE_PRODUCT_SCREEN',
  ONBOARDING_SCREEN: 'ONBOARDING_SCREEN',
  TAB_MAIN_SCREEN: 'TAB_MAIN_SCREEN',
  STACK_HOME_SCREEN: 'STACK_HOME_SCREEN',
  PRODUCT_DETAIL_SCREEN: 'PRODUCT_DETAIL_SCREEN',
  STACK_MAIN_PRODUCT_DETAIL_SCREEN: 'STACK_MAIN_PRODUCT_DETAIL_SCREEN',
  PAYMENT_SCREEN: 'PAYMENT_SCREEN',
};
