export default ActionType = {
  // app loading
  IS_LOADING_TRUE: 'IS_LOADING_TRUE',
  IS_LOADING_FALSE: 'IS_LOADING_FALSE',
  //modal Notification
  IS_ACTIVE_NOTIFICATION_TRUE: 'IS_ACTIVE_NOTIFICATION_TRUE',
  IS_ACTIVE_NOTIFICATION_FALSE: 'IS_ACTIVE_NOTIFICATION_FALSE',
  //Cart
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
  REMOVE_PRODUCT_TO_CART: 'REMOVE_PRODUCT_TO_CART',
  MINUS_PRODUCT_TO_CART: 'MINUS_PRODUCT_TO_CART',
  CLEAR_PRODUCTS_TO_CART: 'CLEAR_PRODUCTS_TO_CART',
};
